### ISSUE TITLE
Binary is now called "main" instead of "http-server" after cargo install

### ISSUE THREAD

**Issue by mstange** [http-server-rs/http-server#11]
**Description**

I tried to follow the readme: I ran `cargo install http-server`. But then I couldn't run `http-server` because no binary with that name was installed. Instead, the installed binary's name is `main`.

```
% cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)
% cargo install --list
http-server v0.3.0:
    main
```

**Environment**

HTTP Server Version: v0.3.0
Operative System: macOS 11.3.1 on M1

**Comment by LeoBorai** [comment]
Hi @mstange ! Thanks for opening an issue and help improve this project!

I will check the issue and let you know when its fixed.

**Comment by LeoBorai** [comment]
@mstange this issue is fixed now. Update your binary to version `v0.3.1` and you will be able to run `http-server` as expected.

I removed the crate and re install it to make sure it works as expected and had this output:

```bash
$ cargo install http-server
  Updating crates.io index
  Downloaded http-server v0.3.1
  Downloaded 1 crate (266.0 KB) in 2.27s
  Installing http-server v0.3.1
  Downloaded memchr v2.4.0
  Downloaded idna v0.2.3
  # ...
  Compiling hyper v0.14.8
  Compiling hyper-staticfile v0.6.0
  Compiling http-server v0.3.1
  Finished release [optimized] target(s) in 3m 54s
  Installing ~/.cargo/bin/http-server
  Installed package http-server v0.3.1 (executable `http-server`)
$ http-server
Serving HTTP: http://127.0.0.1:7878
```

Thanks again! Please, let me know if you have any issues.

This issue is already closed because the linked PR was merged, if you find any trouble please open a new PR unless such trouble is related to this issue. This way we keep issues focused on one topic.

**Comment by mstange** [comment]
I can confirm it works now. Thanks!
